spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 
            client-secret: 
            scope:
              - email
              - public_profile
          google:
            client-id: 
            client-secret:
            scope:
              - email
              - profile